# -*- coding: utf-8 -*-
"""Comparação_de_Grupos_ Teste A/B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psJh4hDNBpik1LKyHKy-I5o0_cMihLqX
"""

import numpy as np
from scipy import stats

import pandas as pd
df = pd.DataFrame({
    'Grupo': ['A'] * 1000 + ['B'] * 1000,
    'Clique': [1]*120 + [0]*880 + [1]*160 + [0]*840
})

# GRUPO A (BOTÃO AZUL)

visitas_a = 1000
click_a = 120

# GRUPO B (BOTÃO VERDE)

visitas_b = 1000
click_b = 160

# TAXAS DE CONVERSÃO
taxa_a = click_a / visitas_a
taxa_b = click_b / visitas_b

tabela = np.array([[120, 880],  # Grupo A: 120 cliques, 880 não cliques
                   [160, 840]]) # Grupo B: 160 cliques, 840 não cliques

"""Cada linha representa um grupo (A e B).
Cada coluna representa um tipo de resposta:
- Primeira coluna: número de cliques (sucesso)
- Segunda coluna: número de não cliques (falha)
Então:
- Grupo A teve 120 cliques e 880 não cliques → total de 1000 visitantes
- Grupo B teve 160 cliques e 840 não cliques → também 1000 visitantes

"""

# TESTE QUI-QUADRADO

chi2, p_valor, _ , _ = stats.chi2_contingency(tabela)

# RESULTADOS

print(f"Taxa de conversão A: {taxa_a:.2%}")
print(f"Taxa de conversão B: {taxa_b:.2%}")
print(f"Valor-p: {p_valor: .5f}")

if p_valor < 0.05:
    print("Diferença estatisticamente significativa. Use o botão verde!")
else:
    print("Diferença não significativa. Mais testes são necessários.")

"""Comparando taxas de conversão"""

