# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roDgeAyptX0Knl1qv3tSLNTYOQ5fJIUC
"""

import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y = [6,7,8,9,10]

plt.plot(x,y)



plt.title("Grafico de linha")
plt.xlabel("Eixo x")
plt.ylabel("Eixo y")

plt.show()

import matplotlib.pyplot as plt

categorias = ['Cat A', 'Cat B', 'Cat C', 'Cat D']
valores = [25,40,30,90]

plt.bar(categorias,valores, color= 'red')

plt.title("Grafico Barra")
plt.xlabel("Categorias")
plt.ylabel("Valores")

plt.legend(['legenda'], loc='upper left')

for i, valor in enumerate(valores):
  plt.text(i, valor +1, str(valor), ha='center')

plt.tight_layout()

plt.show()

